name: plab_first_project
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^1.1.8+4
  http: ^0.12.2
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_native_splash:
  color: "42a5f5"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/splash_plablogo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        
